### ISSUE TITLE
Remove header from qbed file (lower priority)

### ISSUE THREAD

**Issue by marialexandra16** [cmatKhan/callingCardsTools#9]
### Description of feature

The header makes common downstream processes such as concatenating and sorting qbeds clunkier

**Comment by cmatKhan** [comment]
I left the header in b/c qbed isn't a familiar format to anyone except someone who is already familiar with calling cards. Putting the header in helps, in that case. It also makes it convenient to read into Python or R. If you're piping the file into another utility, you can skip the first line with:

```
awk `NR>1' <filename>
```

But, anyone doing a callingcards experiment should figure out what the qbed format is, arguably. I'll go ahead and remove it when I make the other updates

**Comment by cmatKhan** [comment]
done in v1.1.0
